// <auto-generated />
namespace SWKaizenMigrationsCodeDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddBlogUrl : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206031650383_AddBlogUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9ff/b2y4gf58ovios5awqY5oXee5ovqo/S4LDLC6HVenr8nejsPgd5HtmPq+pRQbK/fXK9y7v6zj56U1YXfgtr8Xvl18AF99LKuVnndXr/Kz733zmYfpXfDd+92X7avdt4DCp99dLZs7+19lL5Yl2U2KemD86xs8o/S1aePXrdVnX+eL3MiSD57mbVtXtMknc1yHoKS4tHq09tR4+HdnT1Q4262XFYt07iHfAdV/GsQfd3WxDwfpc+Kd/nseb68aOcW2S+yd+YT+vWj9KtlQbxGL7X1OvcHJ39v7vSruvxZ7vPxXccEfdYgrm2zgqjuzRc+y9+1HTaR9q/z1mvZfJQ64MKzY+awKAa2Lycad0U2jAzdHRCix19kqxURxxMq/SR9LRJ1sv36/aVlITDuTpuI0FhsbU/EodlF3vmWuiZMnxV10z7N2mySYbpOZotes1tQ1vTkE7grmo7epjV+lzeG1cq4L/cMTWE8o4EtSNB4jDpCwiemLvTF19OszOoBYT+pyvViuUlxbIIicujDkE9uD4GFygfAH/Tff3y3M/4usT3R0ZYd9deduk1c321ie7fc3+Hyx8pxN9uTHgtKk49SIsxlMQP7vb5u2nwxRoPx619UnpQFjdc1+CJbFud5076p3uawjSQhX98UWeXbNLPy/832qAAJbrQ8PXN1ezuyvMzq6TyrtxbZuzsfYBveA8776fu+8rpZ6w8qfeG6zz6aTciPeSMIqpn4mvagLwGP7/p+1+OneVNcOBDwwpb5FLrPATVtzpbnlSExjcjHyDTpzMAXeZvNiDDHdVucZ9OWvp7mTcNm+iezck1NTheTfHa2/HLdrtbtcdPki0l57Y/38d3N/bPRC3F+/OWKtfc3MQRCs6Ah5F8un6yLcmbxftZn5SEQ4BGVD8KK3BQCd3FtIb2olrcEpOR7mq/yJaTrTb5YlQSs+XL5OrvMh3G7mYYhxR4/LTIygQufgvKJYvI6o569LqgD/w3XH/1J7EpO/9H/EwAA//9nkDyCaQwAAA=="; }
        }
    }
}
