// <auto-generated />
namespace SWKaizenMigrationsCodeDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206031220233_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9ff/b2y4gf58ovios5awqY5oXee5ovqo/S4LDLC6HVenr8nejsPgd5HtmPq+pRQbK/fXK9y7v6zj56U1YXfgtr8Xvl18AF99LKuVnndXr/Kz733zmYfpXfDd+92X7avdt4DCp99dLZs7+19lL5Yl2U2KemD86xs8o/S1aePXrdVnX+eL3MiSD57mbVtXtMknc1yHoKS4tHq09tR4+HdnT1Q4262XFYt07iHfAdV/GsQfd3WxDwfpc+Kd/nseb68aOcW2S+yd+YT+vWj9KtlQbxGL7X1OvcHJ3/7nT6+6yakP03EQW1WEAU82uGz/F3bmTJp/zpvvZbNR6kDLvwz5tmOYmD7cmx6V/jU8PPdAYZ+/EW2WhFxPAbXT9LXwt0n26/fn3MXAuPutIkwsMXW9kTckl3knW+pa8L0WVE37dOszSYZputktug1uwVlTU8+gbti4uhtWuN3eWNYxMd9GWRoCuMZDWxBTM9j1BESPjHR1RdfT7MyqwcE76Qq14vlJiHeBEVkwochn/QhPL7bwb9LLI/1tWVHlXRJv4lru01s75Z7O1z6WDnmZt3cYyFp8lFKpLksZmCf19dNmy/GaDB+/YvKk7Kg8boGX2TL4jxv2jfV2xx2hjj866t1q8iaZlb+v1m3FyDBjVq8p/pvr5OXl1k9nWf11iJ7d+eb1LN9pXGzth1UtsItn300m5AtfyMIqnr+mnq4z7mP7/q+x+OneVNcOBDwRJb5FDrHATVtzpbnlaExjcjHyDTpTMEXeZvNiDDHdVucZ9OWvp7mTcPm8Sezck1NTheTfHa2/HLdrtbtcdPki0l57Y/38d3N/bOxCXF+/OWKteY3MQRCs6Ah5F8un6yLcmbxftZnwSEQ4BHla8KK3AMCd3FtIb2olrcEpOR7mq/yJaTiTb5YlQSs+XL5OrvMh3G7mYYhxR4/LTIyPQufgvKJYvI6o569LqgD/w3XH/1J7EqO79H/EwAA//8QlkJVbQsAAA=="; }
        }
    }
}
